################################# Default configuration ###################
# provide your domain here
baseURL = "https://docs.nightingaletrading.com/"
# theme
theme = "dot"
# site title
title = "Nightingale Trading Help & Documentation"
# disable language
disableLanguages = []
# google analytics
googleAnalytics = "" # paste your analytics ID here. (Ex: UA-123-45)

# unsafe html
[markup.goldmark.renderer]
unsafe= true

################################# navigation ################################
[[menu.main]]
name = "Faq"
url = "faq"
weight = 1

[[menu.main]]
name = "contact"
url = "contact"
weight = 2

# Dropdown menu
[[menu.main]]
weight = 3
name = "docs"
hasChildren = true

  [[menu.main]]
  parent = "docs"
  name = "Installation"
  url = "installation"
  weight = 1

  [[menu.main]]
  parent = "docs"
  name = "Billing and Pricing"
  url = "billing-pricing"
  weight = 2

  [[menu.main]]
  parent = "docs"
  name = "Features"
  url = "features"
  weight = 3


############################# Default Parameters ##########################
[params]
# logo is for all page
logo = ""
# logo white is for homepage logo, you can use colorful logo too...
logo_white = ""
# when logo is empty, it will shown your site title

# customize color
primary_color = "#008b8b"
body_color = "#f9f9f9"
text_color = "#636363"
text_color_dark = "#242738"
white_color = "#ffffff"
light_color = "#f8f9fa"

# font family
font_family = "lato" # Choose font family from : https://fonts.google.com/

# contact form action
contact_form_action = "#" # contact form works with : https://formspree.io


############################## social links ##############################
[[params.social]]
icon = "ti-twitter-alt" # themify icon pack : https://themify.me/themify-icons
link = "https://twitter.com/NightingaleTra3"


################################ English Language ######################
[Languages.en]
languageName = "En"
languageCode = "en-us"
weight = 1
home = "Home"
copyright = ""

# banner
[Languages.en.params.banner]
title = "Support Center & Knowledge base"
subtitle = ""
bg_image = "images/banner.jpg"
placeholder = "Have a question? Just ask here or enter terms"

# call to action
[Languages.en.params.cta]
enable = true
title = "Didn't find an answer to your question?"
content = ""
# call to action button
[Languages.en.params.cta.button]
enable = true
label = "contact us"
link = "https://www.nightingaletrading.com/contact"